### ISSUE TITLE
Intermittent 401 Unauthorized errors with our IBM Cloud IAM PEP integration

### ISSUE THREAD

**Issue by agkhare** [IBM/java-sdk-core#142]
Hello Folks,

We have a JAVA Spring Boot Microservice integrated with IBM Cloud IAM PEP. As part our integration , we have implemented java.util.function.Supplier interface which uses com.ibm.cloud.sdk.core.security.IamAuthenticator.

We have a logic that checks whether token needs refresh and then calls IamAuthenticator.requestToken() method. However what we noticed is that this call intermittently fails with 401 Unauthorized error. Also noticed that, looks like there are no retries in IamAuthenticator. Just wanted to seek help on how can we prevent such intermittent errors.

**Comment by agkhare** [comment]
Hi @padamstx ,thanks for your response. So looking at the logic, it appears that. If IAMAuthenticator.requestToken() method hits any exception, there is no retry and the Exception thus caught is simply stored as  member in IAMToken object and returned to the caller:

` try {
      token = invokeRequest(builder, IamToken.class);
    } catch (Throwable t) {
      token = new IamToken(t);
    }
    return token;`

Now if caller uses token generated like above for calling any API, it fails with 401 error. What is unclear in this case, what could be such cases wherein token endpoint would return exception/s .

**Comment by padamstx** [comment]
> Now if caller uses token generated like above for calling any API, it fails with 401 error. What is unclear in this case, what could be such cases wherein token endpoint would return exception/s .

I'm not sure what circumstances would lead the IAM token service to return an error, other than perhaps an invalid apikey or some other user-type error that might occur when configuring the IamAuthenticator instance.   Could you modify your code slightly so that it displays exception contained in the IamToken instance returned by requestToken()  (i.e. you can call IamToken.getException() method).   Hopefully the exception and error message would give us a clue as to why that occurs.

**Comment by padamstx** [comment]
@Andras-Csanyi Could you please start to look into this situation and try to diagnose what's going on?

**Comment by Andras-Csanyi** [comment]
@agkhare Could you extract the exception from your code?

**Comment by padamstx** [comment]
Closing out this issue as I've been separately discussing this issue on slack.
If a problem in the Java core is identified, we can re-open this issue or open up a new more specific issue.
