### ISSUE TITLE
bump okhttp3 from 4.9.3 to 4.10.0

### ISSUE THREAD

**Issue by mojito317** [IBM/java-sdk-core#180]
I would like to ask you to upgrade okhttp3 because they have resolved a kotlin CVE in https://github.com/square/okhttp/pull/7225 which is the part of the `4.10.0` release.

**Comment by padamstx** [comment]
I'll try to get to this today.

**Comment by padamstx** [comment]
PR: https://github.com/IBM/java-sdk-core/pull/181
