### ISSUE TITLE
Report security vulnerabilities found via HCL AppScan.

### ISSUE THREAD

**Issue by sann-jay** [IBM/java-sdk-core#182]
Hi Team,

I work for an IBM product and we bundle our application with various IBM Cloud jars. I just wanted to know how we could report some security vulnerabilities found via HCL AppScan in various IBM Cloud JAR files that we bundle in our application.

I can share the reports internally, if needed.

Thanks!

![](https://user-images.githubusercontent.com/2337153/174324635-1268029a-589d-4d5c-89ee-fc07a07a88e5.png)

**Comment by padamstx** [comment]
This vulnerability has been resolved as a false positive.
