### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [IBM/java-sdk-core#24]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by padamstx** [comment]
We currently use
`sudo: required`
Is there another way to specify this?

**Comment by cclauss** [comment]
Just remove the line because __sudo__ is __always__ available now in Travis

**Comment by padamstx** [comment]
gotcha... thanks!

**Comment by padamstx** [comment]
This change has been completed via PR #24
