### ISSUE TITLE
Allow for authentication for configured proxy

### ISSUE THREAD

**Issue by lpatino10** [IBM/java-sdk-core#44]
Originally submitted in the Watson Java SDK: https://github.com/watson-developer-cloud/java-sdk/issues/1071)

**TLDR:** We allow users to configure the HTTP client, and one configuration option is setting an OkHttp proxy. However, we don't offer a way to set up authentication for this proxy, when we did in the past.

**Comment by lpatino10** [comment]
@marloncarvalho this is the repo for the core of the Java SDK, where we actually have the logic for configuring the HTTP client. If you'd like to make a PR (which would be great!), this is the place to do it.

Just wanted to confirm @padamstx, this seems like a pretty reasonable addition to the core, right?

**Comment by padamstx** [comment]
Yep

**Comment by marloncarvalho** [comment]
Great! I've already forked the repository and started working on this.

**Comment by marloncarvalho** [comment]
Hi again! I've finished it. I would like to know how to proceed with this pull request. I followed all code conventions and documented everything. I also changed the HttpConfigOptions tests however, I couldn't find any test for the class HttpClientSingleton.

Should I request a PR to the master branch or to any other branch? I made all the changes in the Master branch in the forked repo.

**Comment by lpatino10** [comment]
Awesome! Go ahead and make the PR to `master`. We'll need the changes in another place but I can take over that once we've reviewed and approved the changes. You can go ahead and tag me for the review.

**Comment by lpatino10** [comment]
Closed as this has been added and released.
