### ISSUE TITLE
Okio package vulnerable to CWE-327

### ISSUE THREAD

**Issue by mediumTaj** [IBM/java-sdk-core#97]
An issue was opened in the Watson Java SDK related to Okio package in the core.

https://github.com/watson-developer-cloud/java-sdk/issues/1127

**Comment by jorge-ibm** [comment]
@mediumTaj - I'm not seeing this in the latest app scan on the core: https://github.ibm.com/arf/planning-sdk-squad/issues/2242#issuecomment-24586808. I see you guys are using an older version of the core, 8.1.0. Is that correct?

**Comment by jorge-ibm** [comment]
Discussed with @mediumTaj. This cve seems to have been fixed in later versions of okio and the latest version of the core uses okio v2.7. Upgrading to the latest version of the core should fix this cve. Closing.

**Comment by mediumTaj** [comment]
what is the lowest version of the core that uses okio 2.7?
